repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
        args: [--no-update]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args: [--respect-gitignore]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [-q, --check]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.327
    hooks:
    - id: pyright
