[tool.poetry]
name = "daisybell"
version = "0.4.4-dev"
description = "A scanner that will scan your AI models for problems. Currently it focuses on bias testing. It is currently alpha."
authors = ["Your Name <you@example.com>"]
license = "Apache-2.0"
readme = "README.rst"
classifiers=[
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.8.1 <3.11"
torch = "^2.0.0"
transformers = "^4.30.1"
pandas = "^2.0.2"
tabulate = "^0.9.0"
types-tabulate = "^0.9.0.2"
dataframe-image = "^0.1.5"
seqeval = "^1.2.2"
datasets = "^2.13.1"
tensorboard = "^2.13.0"
pysbd = "^0.3.4"
grpcio = "<1.56.1"
sentencepiece = "^0.1.97"
protobuf = "^3.19.1"

pytest = { version = "7.3.2", optional = true }
pytest-cov = { version = "4.1.0", optional = true }
pytype = { version = "2023.6.16", optional = true }
flake8 = { version = "6.0.0", optional = true }
pdbpp = {version = "^0.10.3", extras = ["test"]}

[tool.poetry.extras]
test = [
"pytest",
"pytest-cov",
"pytype",
"flake8",
"pdbpp"
]

[tool.poetry.scripts]
daisybell = 'daisybell.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
