[tool.poetry]
name = "daisybell"
version = "0.4.4-dev"
description = "A scanner that will scan your AI models for problems. Currently it focuses on bias testing. It is currently alpha."
authors = ["Your Name <you@example.com>"]
license = "Apache-2.0"
readme = "README.rst"
classifiers=[
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.8.1 <3.11"
torch = "^1.13.1"
transformers = "^4.26.1"
pandas = "^1.5.3"
tabulate = "^0.9.0"
types-tabulate = "^0.9.0.1"
dataframe-image = "^0.1.5"
seqeval = "^1.2.2"
datasets = "^2.10.0"
tensorboard = "^2.12.0"
pysbd = "^0.3.4"
grpcio = "<1.51.0"

pytest = { version = "7.2.1", optional = true }
pytest-cov = { version = "4.0.0", optional = true }
pytype = { version = "2023.2.17", optional = true }
flake8 = { version = "6.0.0", optional = true }

[tool.poetry.extras]
test = [
"pytest",
"pytest-cov",
"pytype",
"flake8"
]

[tool.poetry.scripts]
daisybell = 'daisybell.__main__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
