name: docker-test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: |
        docker build -f Dockerfile . -t iqtlabs/daisybell:latest
        docker run -t iqtlabs/daisybell:latest --help
        