name: release

on:
  push:
    branches: main
    tags: "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Build and publish packages
        id: build_and_publish_packages
        run: |
          sudo apt-get update && \
          sudo apt-get install -yq --no-install-recommends python3-pip python3 python3-dev python3-setuptools && \
          poetry build && poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_TOKEN }}
        if: github.repository == 'iqtlabs/daisybell' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
