name: secrets

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Scan for secrets
      id: scan
      uses: IQTLabs/workflows/secret-scan@main

    - name: Fail if found
      if: steps.scan.outputs.verified-secrets != 0
      uses: actions/github-script@v6
      with:
        script: |
            core.info(`Number of verified secrets: ${{steps.scan.outputs.verified-secrets}}`)
            core.info(`Number of unverified secrets: ${{steps.scan.outputs.unverified-secrets}}`)
            core.setFailed('Secrets found. Please check the uploaded report')
