name: secrets

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Scan for secrets
      id: scan
      uses: IQTLabs/workflows/secret-scan@main
